spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
#  cloud:
#    gateway:
#      routes:
#        - id: account-management
#          uri: lb:http://MEMBER-MANAGEMENT
#          predicates:
#            - Path=/api/v1/artemis/account/secured/**
#          filters: []
#        - id: account-management-public
#          uri: lb:http://MEMBER-MANAGEMENT
#          predicates:
#            - Path=/api/v1/artemis/account/public/**
#          filters: []
